sudo: false
language: rust
rust: nightly
addons:
  apt:
    packages:
    - libcurl4-openssl-dev
    - libelf-dev
    - libdw-dev
before_script:
- |
  pip install 'travis-cargo<0.2' --user &&
  export PATH=$HOME/.local/bin:$PATH
script:
- travis-cargo build
- travis-cargo test
- travis-cargo bench
env:
  global:
  - TRAVIS_CARGO_NIGHTLY_FEATURE=""
  - secure: iEGoVGb3OeqSqP4UP7nbLtMEmGi9JgI0nxjrpRrSg22pCCa+lMIIiYp9gY2558pwAbcxaJpahmTt3lYqe2wdKfXlGWRB7Tz99FR8lX+vRXpgxDLg1Sz8BAnN7X9bu+AGL/INwYOe6tVncXcQgKn4uSTYa001CqhlwPzMmtGSw/w=
  - secure: eKEXvvZrTIKGV7LouFW0EfjFPd09OgEI3Y6Z5QsWdEdv73zMvXzjz9xHu+9AmYirI8m/e0v2/RXefP/elcxjLKBa61b1MC/shQPjpbaqC4Y6UTQh5If1X/QN88cbc+VldD2dKgjP5gRX72TAfHoO466NLIxxigKkZJQsOawOVUs=
after_success:
- travis-cargo coveralls --no-sudo
- bash <(curl https://codecov.io/bash)
before_deploy:
- travis-cargo doc
- travis-cargo doc-upload
- cargo build --release
- cargo package
- cargo publish --token $CRATES_TOKEN
deploy:
  provider: releases
  api_key:
    secure: hXEp+2VHRznxkeaJhb3i9wld/Nw40U2OOYewbyBmpxKEyvP78Ae42kzKOaOHqgFj54BgAb7fQVHO7bdjYcTSum75rh4iz0dplmKTZKWKj1NO1HgvXbwTdfN6VkALttoTMmegW9ngzxZxkrpF3ezPlADglv41mkzW5Ewwf4tPhJQ=
  file: /target/release/seax
  on:
    repo: hawkw/seax
